### ISSUE TITLE
urls open from second attempt

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#143]
It occurs for example here #98 but not only

Following from https://redmine.astro.unige.ch/issues/25485 - it was first suspected to be a site issue.

**Comment by motame** [comment]
Fixed on dev and pushed to github.

**Comment by volodymyrss** [comment]
It is better, thank you!
There is still a case: when doing "open link in new tab" simultaneously  for several links: only some complete opening, a bit randomly. Maybe it's more complex.

**Comment by motame** [comment]
Strange !
I don't see it at all.
I opened many from https://www.isdc.unige.ch/integral/ibas/cgi-bin/ibas_acs_web_mtm.cgi?month=2022-03
and all of them open properly.

**Comment by volodymyrss** [comment]
For me, from this page, the problem still present.

Even more strange, sometimes, this happens:

![image](https://user-images.githubusercontent.com/3909535/161709182-1dae3afa-fa10-4820-9eaa-b1ed67616dee.png)

I.e. isgri request while SPI-ACS is intended.

I also can see that for a single tab, two `run_analysis` requests are sent. One for ISGRI  tab, and it fails. Another one - with  SPI-ACS.

I hope this information is useful.
If you think it can be helpful, we can also have a call or even meet on Thursday.

**Comment by motame** [comment]
I finally succeed to reproduce it !
Fixed on server side and introduced a bug in client side :-).
I am back on it ...

**Comment by motame** [comment]
I have been fooled by the routine "validate" of the library bootstrapValidator.
It does more than validating : submits the form if it is valid ;-) !
That is why 2 simultaneous requests were submitted, the first one while validating and submits the wrong instrument !
The second one which is explicit in the code is supposed to do the job, submit the target instrument only.
Instead of relying on this routine, I am validating now explicitly each of the inputs of the two forms (common parameter form + instrument form).
This time is the right one I hope ! 🙏🏻

Volodya, would you please test again  😊 ...

**Comment by volodymyrss** [comment]
It's better thank you! There is no double `run_analysis`, and no strange error.

But 30%-50% of the time, run_analysis is not run a all, fields are not changed. The page remains unchanged. So you do not see this anymore, even if opening e.g. 6 tabs at once?

**Comment by motame** [comment]
This time it should be your browser ! 😂
On mine it's working perfectly ...

**Comment by volodymyrss** [comment]
I perfectly believe it works in your browser!

The problem is that people might have other browsers. I do, apparently. Did you try in firefox?
Maybe it helps if you explain a bit so I can diagnose too?

**Comment by volodymyrss** [comment]
Ok I suppose we close this as per discussion last  week.
